on:
  push:
    branches:
    - release/*

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "dev"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "[AUTO] Pushing ${{ github.head_ref || github.ref_name }}  into dev" 
        pr_label: "auto-pr"
