on:
  push:
    branches:
    - release/*

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "[AUTO] Pushing ${{ github.head_ref || github.ref_name }}  into master" 
        pr_label: "auto-pr"
    - name: pull-request-for-deploy-on-test-env
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "qwe"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "[AUTO] Pushing ${{ github.head_ref || github.ref_name }}  into qwe" 
        pr_label: "auto-pr"
